org: ${env:ORG_NAME}
service: api-bebes

provider:
  name: aws
  region: us-east-1
  runtime: python3.13
  timeout: 30
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole
  environment:
    TABLE_USUARIOS: t_usuarios
    TABLE_TOKENS: t_tokens_acceso
    TABLE_PRODUCTOS: t_productos
    TABLE_COMPRAS: t_compras

functions:

  # === USUARIOS ===
  loginUsuario:
    handler: LoginUsuario.lambda_handler
    events:
      - http:
          path: /usuario/login
          method: post
          cors: true

  registrarUsuario:
    handler: RegistrarUsuario.lambda_handler
    events:
      - http:
          path: /usuario/signup
          method: post
          cors: true

  validarUsuario:
    handler: ValidarUsuario.lambda_handler
    events:
      - http:
          path: /usuario/validar
          method: post
          cors: true

  # === PRODUCTOS (Node.js) ===
  listarProducto:
    handler: ListarProducto.handler
    runtime: nodejs20.x
    events:
      - http:
          path: /producto/listar
          method: post
          cors: true

  crearProducto:
    handler: CrearProducto.handler
    runtime: nodejs20.x
    events:
      - http:
          path: /producto/crear
          method: post
          cors: true

  buscarProducto:
    handler: BuscarProducto.handler
    runtime: nodejs20.x
    events:
      - http:
          path: /producto/buscar
          method: post
          cors: true

  modificarProducto:
    handler: ModificarProducto.handler
    runtime: nodejs20.x
    events:
      - http:
          path: /producto/modificar
          method: post
          cors: true

  eliminarProducto:
    handler: EliminarProducto.handler
    runtime: nodejs20.x
    events:
      - http:
          path: /producto/eliminar
          method: post
          cors: true

  # === COMPRAS ===
  registrarCompra:
    handler: RegistrarCompra.lambda_handler
    events:
      - http:
          path: /compra/registrar
          method: post
          cors: true

  listarCompras:
    handler: ListarCompras.lambda_handler
    events:
      - http:
          path: /compra/listar
          method: post
          cors: true
